### ISSUE TITLE
Content box color changes

### ISSUE THREAD

**Issue by fmaussion** [executablebooks/sphinx-book-theme#240] opened 2020-10-27 16:22 UTC
**Describe the bug**

The color of the content boxes changed after upstream changes in the pydata theme: https://github.com/executablebooks/meta/discussions/168

**Expected behavior**

I think that book-theme needs to be more conservative than that and keep the colors as they were.

**Additional context**

@choldgraf suggest a fix along these lines: https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/customizing.html#theme-variables 

I'm not sure I'll have time to dig into this right away, so if someone knows how to do that please go ahead!

**Comment by choldgraf** [comment] 2020-11-01 21:37
I think this is closed by #246  - @fmaussion wanna double check that the colors are correct now?

**Comment by fmaussion** [comment] 2020-11-02 13:02
@choldgraf I just tested this and for me now all the boxes are grey

**Comment by choldgraf** [comment] 2020-11-02 13:03
hmm that's weird, and you're on the latest pydata theme + sphinx book theme? they should look like the boxes here:

https://sphinx-book-theme.readthedocs.io/en/latest/reference/demo.html#admonitions

**Comment by fmaussion** [comment] 2020-11-02 13:09
Ups sorry for the noise. I'm quite sure I was on latest but to be sure I deinstalled and reinstalled everything and now it works.

Thanks for checking!

**Comment by choldgraf** [comment] 2020-11-02 13:12
hooray!

**Comment by pradyunsg** [comment] 2020-11-02 13:15
@choldgraf Should we declare a minimum requirement on the pydata theme, now that we're depending on something that's only available in newer versions?

**Comment by choldgraf** [comment] 2020-11-02 15:36
well we already do I think (`~=0.4.1`)...but we need to bump this again whenever the next version comes out. I actually jumped the gun a bit and I think this color box change may still be in `master` but not released, but I could be wrong. Basically I am confused.

**Comment by fmaussion** [comment] 2020-11-02 15:45
> Basically I am confused.

Same - It actually still does not work for me. I had to revert sphinx pydata to 0.4.1 to get my colors to work (while at latest for jupyter-book and sphinx-jupyter-book)

**Comment by choldgraf** [comment] 2020-11-04 16:03
ok @fmaussion can you try this again on master? I think that https://github.com/executablebooks/sphinx-book-theme/issues/240 may fix this

**Comment by fmaussion** [comment] 2020-11-04 16:08
Will do - do I need a specific version of pydata sphinx theme for that?

**Comment by fmaussion** [comment] 2020-11-04 16:09
Oh I've seen you pinned 0.4.1 in https://github.com/executablebooks/sphinx-book-theme/pull/249

**Comment by choldgraf** [comment] 2020-11-04 16:09
try it on master for both - that fix in #249 should not do anything on 0.4.1, and should provide correct colors on the new pydata version when it's released

**Comment by fmaussion** [comment] 2020-11-04 16:26
```
$ pip list
jupyter-book                      0.8.3
pydata-sphinx-theme               0.4.2.dev0
sphinx-book-theme                 0.0.39b1 
```

Also, the results I different wether I install latest `sphinx-book-theme` via `pip install -e .` on cloned master (the results above) or via `pip install --upgrade git+https://github.com/executablebooks/sphinx-book-theme` (different colors, also wrong).

This is all super confusing to me and I wonder if I should start from a fresh environment (although I can't really see what I'm doing wrong here). 

Note also this problem that I have since I tried to upgrade too many things and can't recover from: https://github.com/executablebooks/sphinx-exercise/issues/28 

(sorry for the mess)

Results in something better, but not quite it:

![image](https://user-images.githubusercontent.com/10050469/98136940-bd658300-1ec1-11eb-9125-501d13c2abca.png)
(should be red)

![image](https://user-images.githubusercontent.com/10050469/98137008-ceae8f80-1ec1-11eb-846c-cc92ce1b06da.png)
(is OK)

![image](https://user-images.githubusercontent.com/10050469/98137058-dd954200-1ec1-11eb-8458-afb53ab2ba2f.png)
(should be blue)

**Comment by fmaussion** [comment] 2020-11-04 16:27
(sorry I edited my original post which was not in order)

**Comment by choldgraf** [comment] 2020-11-04 17:00
ah darn - OK I think the problem is that the pydata theme also changed this behavior, will try to fix

**Comment by choldgraf** [comment] 2022-02-20 20:01
ok I believe this is now resolved

**Closed by choldgraf** 2022-02-20 20:01 UTC
Labels: bug, :label: design
