### ISSUE TITLE
Issue with Left ToC and mobile (e.g. jupyter-book gallery)

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/sphinx-book-theme#303] opened 2021-03-17 14:42 UTC
Go-to https://executablebooks.org/en/latest/gallery.html and "squeeze" the window, it's not working like the SBT main page: it does not appear above the main body. and you get lots of space on the left when hidden:

![image](https://user-images.githubusercontent.com/2997570/111484208-d286d400-8735-11eb-9192-6ba09fbcf770.png)

Presumably since https://github.com/executablebooks/sphinx-book-theme/commit/76fe7e77883d8029f8f253387b92f28d202fb59e?

cc @choldgraf and @DrDrij

**Comment by choldgraf** [comment] 2021-03-17 15:08
Ah weird, I didn't notice that in the PR. I think it applies to other pages than just the gallery.

**Comment by DrDrij** [comment] 2021-03-17 20:35
Thanks for identifying. This occurs on pages without a right page TOC.
I can put together a PR to address these pages this evening.

Are there any such pages in the tox tests I can use for testing?

**Comment by chrisjsewell** [comment] 2021-03-17 21:14
Cheers

> Are there any such pages in the tox tests I can use for testing?

I don't know off-hand I'm afraid. Of course feel free to create one if not

**Comment by DrDrij** [comment] 2021-03-18 10:03
Hmm, on closer inspection it appears it is an issue with how bootstrap is loaded.

https://sphinx-book-theme.readthedocs.io/en/latest/configure.html
https://executablebooks.org/en/latest/gallery.html

These two sites have the same sphinx-book-theme custom scss, but they cascade bootstrap differently (maybe different versions?). It's hard for me to tell where the issue is on `executablebooks.org`. 

What I'm amending is using `id` over `class` for our custom theme css so that it has higher priority.

However, this bug does highlight the potential conflicts with bootstrap. As there is now a set layout for the sphinx-book-theme, I suggest the basic css/js we rewrite with our own classes (but keep bootstrap for anything additional).

<img width="1480" alt="image" src="https://user-images.githubusercontent.com/5886045/111607895-c7fb3600-882c-11eb-81d2-eddbc0648e99.png">

**Comment by choldgraf** [comment] 2021-03-18 15:29
@DrDrij thanks for this analysis - it feels related to https://github.com/executablebooks/meta/issues/279 as well (which would I think remove our dependency on Bootstrap)

**Comment by DrDrij** [comment] 2021-03-29 04:58
Tested `https://executablebooks.org/en/latest/gallery.html` locally with latest `sphinx-book-theme` css: [PR](https://github.com/executablebooks/sphinx-book-theme/pull/305)

**Comment by choldgraf** [comment] 2022-01-08 23:14
I believe this was closed by https://github.com/executablebooks/sphinx-book-theme/pull/305

**Closed by choldgraf** 2022-01-08 23:14 UTC
Labels: bug
