### ISSUE TITLE
Support non-github repositories

### ISSUE THREAD

**Issue by akhmerov** [executablebooks/sphinx-book-theme#119] opened 2020-06-02 22:21 UTC
This is a continuation from #114, following #118.

Several places now hard-code github-specific information. For example #118 introduces the github icon in the top bar, and the schema for pre-populating issue with parameters.

I realize that github is the main priority for this project, however I'd like to know:

- If support of other repository types is on the roadmap?
- What would be the most reasonable way to configure this?

For example if one wanted to adjust #118 to support bitbucket or gitlab, they would need to make the repository icon customizable (instead of `fa-github`), and change the schema for pre-populating the issue title and description. This is all doable, but I'd like to know how would the user control it? Would there be a single "repository_type" configuration key?

**Comment by choldgraf** [comment] 2020-06-02 23:06
Yes for sure - just a matter of hours in the day, and I think GitHub is the main one to prioritize.

I think the thing to do is to start using *functions* to generate values in the HTML, and then use python logic to determine whether the outputs should be one thing or another.

**Comment by choldgraf** [comment] 2022-06-09 14:30
I think this is a duplicate of:

- https://github.com/executablebooks/sphinx-book-theme/issues/114

that one has more comments so I'll close this one

**Closed by choldgraf** 2022-06-09 14:30 UTC
