### ISSUE TITLE
:align: center does not work for images

### ISSUE THREAD

**Issue by DavidPowell** [executablebooks/sphinx-book-theme#141] opened 2020-08-03 09:17 UTC
**Describe the bug**

When using `:align: center` with images (SVG) from a jupyter-book document (myst source file), the image remains aligned to the left.

I am able to overcome this by adding the following to my custom.css:

```css
img.align-center {
   margin-left: auto;
   margin-right: auto;
   text-align:center;
   display:block;
}
```

I don't fully understand why this solution works, so I'm reluctant to submit it as a PR.

**Environment**
jupyter-book                   0.7.3
Sphinx                         2.4.4
sphinx-book-theme              0.0.33
sphinx-bootstrap-theme         0.7.1
sphinx-copybutton              0.2.11
sphinx-rtd-theme               0.4.3
sphinx-thebe                   0.0.7
sphinx-togglebutton            0.2.0

**Comment by choldgraf** [comment] 2020-08-03 15:03
hmmm I wonder if this is an SVG vs PNG thing. Do PNGs work for you?

**Comment by DavidPowell** [comment] 2020-08-04 01:02
@choldgraf I now have a minimal working example, and it shows the problem for png files:

* Create a template jupyter-book project with `jupyter-book create template`
* Add the following lines to `markdown.md`

````
```{image} logo.png
:align: center
```
````
* Resulting output below shows that image is not centered
![image](https://user-images.githubusercontent.com/1106295/89241310-d69c3080-d641-11ea-98d9-02ff9e4b47ee.png)

**Comment by DavidPowell** [comment] 2020-08-04 02:34
Possibly also related, I am having similar problems with alignment of figures too. I'll report here when I get the time to create a clear minimum example.

**Comment by choldgraf** [comment] 2020-08-04 15:28
Hmmm - it seems like `align` works for figures but may not apply to `{image}` directives. @najuzilu did you run into this at all?

**Comment by najuzilu** [comment] 2020-08-05 09:54
According to the [Sphinx documentation](https://docutils.sourceforge.io/docs/ref/rst/directives.html#image) `align` should also work for `image` directives. It looks like the option is set through css under their basic theme [here](https://github.com/sphinx-doc/sphinx/blob/3.x/sphinx/themes/basic/static/basic.css_t#L280). I think one way forward would be to include these options under [sphinx-book-theme.scss](https://github.com/executablebooks/sphinx-book-theme/blob/master/sphinx_book_theme/static/sphinx-book-theme.scss) (similarly to how the `align` option for `figure` is handled).

However, I wonder if it makes sense to add the `align` option for `figure` and `image` directives under a JB basic theme. The `align` options are a no-brainer and it doesn't make sense to incorporate them in every theme. What do you think @choldgraf?

**Comment by choldgraf** [comment] 2020-08-17 00:57
oops, just realized I didn't get back on this - I think for now we should just add the right CSS classes to the sphinx-book-theme to make sure that this works, and we can think about how to generalize for other themes later. Does that make sense?

**Comment by mmcky** [comment] 2021-02-23 05:18
This seems to be related: https://github.com/executablebooks/jupyter-book/issues/1204

**Comment by DrDrij** [comment] 2021-02-25 08:25
Hi @choldgraf! I've added the CSS for now https://github.com/executablebooks/sphinx-book-theme/pull/292.
If you'd prefer a default unstyled `img` and explicit use of `align-center` please let me know!

**Comment by leneym** [comment] 2021-04-07 17:28
Hey guys, this new CSS change makes my small images look really wonky when they appear between paragraphs, so I was wondering if we could change back to left aligning by default? That way, for those who want to center images, they can add a directive to do so?

**Comment by leneym** [comment] 2021-04-07 17:29
![image](https://user-images.githubusercontent.com/10622919/113909092-26f8fe80-978c-11eb-9e6c-b06191d34ff1.png)

**Comment by leneym** [comment] 2021-04-07 17:30
Please remember that changing the CSS impacts lots of different users. Thanks.

**Comment by choldgraf** [comment] 2021-04-10 00:42
@leneym - sorry for the confusion there, I believe that this was the intended behavior since that's how the `figure` directive was working. If you add `align: left` then they should snap back to the left

(closing since this one is fixed up)

**Closed by choldgraf** 2021-04-10 00:42 UTC
Labels: bug
