### ISSUE TITLE
RTD render doesn't show a `.svg` logo?

### ISSUE THREAD

**Issue by goodboy** [executablebooks/sphinx-book-theme#365] opened 2021-08-03 15:24 UTC
### Describe the problem

A readthedocs render doesn't seem to show an `.svg` logo?

Not sure where to look for the root cause of this.
Could it be some kind of rtd config we're missing?

A manual inspection of a local html versus rtd shows differences in the tree.

### Link to your repository or website

https://tractor.readthedocs.io/en/latest/

### Steps to reproduce

We're expecting it to look like:

![screenshot-2021-08-03_11-23-27](https://user-images.githubusercontent.com/291685/128042062-1f9ca433-f875-4d29-b1e5-079a91ce997e.png)

### The version of Python you're using

3.9

### Your operating system

linux

### Additional context

I'll put up the html diff of interest if needed?

**Comment by goodboy** [comment] 2021-08-03 15:28
Yeah this entire section seems to be missing from rtd version?

```html
<div class="col-12 col-md-3 bd-sidebar site-navigation show" id="site-navigation">
    
        <div class="navbar-brand-box">
<a class="navbar-brand text-wrap" href="#">
  
  <img src="_static/tractor_logo_side.svg" class="logo" alt="logo">
  
  
  <h1 class="site-logo" id="site-title">structured concurrent Python</h1>
  
</a>
</div>
```

**Comment by chrisjsewell** [comment] 2021-08-03 15:31
Possibly related to https://github.com/executablebooks/sphinx-book-theme/pull/364#issuecomment-891812672

when you say it doesn’t show for svg, is this because it does show for other image formats?

**Comment by chrisjsewell** [comment] 2021-08-03 15:50
> Ok so `logo_url` is the issue?

well it shouldn't be in principle, since you are not using sphinx v4, but can always give it a try.

I'd note that I was literally just adding a new SVG logo to some of our other documentation, and this seems to be working ok:

- https://github.com/executablebooks/jupyter-cache/pull/74/commits/35190654a08c4123cff727471acc65e22a8f0919
- https://jupyter-cache--74.org.readthedocs.build/en/74/

**Comment by goodboy** [comment] 2021-08-03 15:56
> https://jupyter-cache--74.org.readthedocs.build/en/74/

Lol indeed it seems to be there.
This is rtd top level domain though right?

**Comment by goodboy** [comment] 2021-08-03 15:59
Yah config for you:
https://github.com/executablebooks/jupyter-cache/commit/35190654a08c4123cff727471acc65e22a8f0919#diff-85933aa74a2d66c3e4dcdf7a9ad8397f5a7971080d34ef1108296a7c6b69e7e3R63

Looks the same as ours?
https://github.com/goodboy/tractor/blob/master/docs/conf.py#L91

Oddly the favicon looks fine?

**Comment by goodboy** [comment] 2021-08-03 16:03
Oh wait, this is what I see on https://jupyter-cache--74.org.readthedocs.build/en/74/

![screenshot-2021-08-03_12-03-10](https://user-images.githubusercontent.com/291685/128048459-1db1640b-c44d-4ee7-9882-922fc0416b9c.png)

Not sure if it's missing something?

**Comment by chrisjsewell** [comment] 2021-08-03 16:07
Yep I have `"logo_only": True` in the `html_theme_options`, so no html title will show

One other thing I noticed, that may not have any relevance here, but you don't use an RTD configuration file e.g. https://github.com/executablebooks/jupyter-cache/blob/master/.readthedocs.yml

**Comment by pradyunsg** [comment] 2021-08-06 08:30
What version of Sphinx are you building with? ReadTheDocs defaults to shipping with Sphinx 1.8, which... might be the culprit here?

**Comment by choldgraf** [comment] 2022-02-09 00:11
I believe that this is because you're using a custom `html_sidebars` variable, and not including the `sidebar-logo.html` in there:

https://github.com/goodboy/tractor/blob/26bebc42b7d654c7873e50d76eeb72c0a7d7cdd0/docs/conf.py#L64-L85

See these docs for the stuff you can include: https://sphinx-book-theme.readthedocs.io/en/latest/customize/sidebar-primary.html#default-sidebar-elements

closing this as I think it's a config issue, not a bug in the theme

**Closed by choldgraf** 2022-02-09 00:11 UTC
Labels: bug
