### ISSUE TITLE
"Strong" text is no different from regular text

### ISSUE THREAD

**Issue by nathancarter** [executablebooks/sphinx-book-theme#122] opened 2020-06-12 13:48 UTC
**Describe the bug**
Text marked with `<strong>...</strong>` (obtained by `**...**` in Markdown in jupyter-book) looks just like regular text.

**To Reproduce**
1. Surround some text in a jupyter-book project with double asterisks.
2. Compile the project to a book.
3. Visit the generated website in the browser.
4. Notice that the marked text does not appear different from the surrounding text.
5. Inspect the text using the browser's developer tools.
6. Note that, while there are indeed `<strong>...</strong>` tags around the text.

**Expected behavior**
Strong text should appear emphasized, typically using bold.

The screenshot below was generated from the following Markdown:
```markdown
## Functions

**Definition:** A *function* is any method for taking a list of inputs and determining the corresponding output.
```

![Screen Shot 2020-06-12 at 9 45 31 AM](https://user-images.githubusercontent.com/1316622/84509353-9186fe00-ac91-11ea-89cd-a69fe2180e4c.png)

**Environment (please complete the following information):**
 - Python Version 3.7.3
 - Output of `pip show jupyter-book` says the version is 0.7.0b4.dev0

**Comment by chrisjsewell** [comment] 2020-06-12 14:23
I transferred it 😄

**Comment by choldgraf** [comment] 2020-06-12 14:24
Hmmm, I just tried this on the latest jupyter book and it worked fine for me, this is what I got:

![image](https://user-images.githubusercontent.com/1839645/84513039-bc675700-ac7d-11ea-89b1-28d34ad9a20e.png)

can you try upgrading jupyter book `pip install -U jupyter-book` and re-building?

(also after you upgrade you should be able to do `jupyter-book --version`)

**Comment by nathancarter** [comment] 2020-06-12 16:06
This did not solve the problem for me.

```
$ jupyter-book --version
Jupyter Book: 0.7.0
MyST-NB: 0.8.1
Sphinx Book Theme: 0.0.23
MyST-Parser: 0.8.1
Jupyter-Cache: 0.2.1
```

**Comment by choldgraf** [comment] 2020-06-12 16:37
Hmmm, I am not sure what to tell you, it's hard to fix without being able to reproduce the bug. Could you post a link to a website you've built where this issue shows up?

**Comment by nathancarter** [comment] 2020-06-12 16:55
Sure.
Page: https://nathancarter.github.io/MA346-course-notes/_build/html/chapter-2-mathematical-foundations.html
Repo: https://github.com/nathancarter/MA346-course-notes

**Comment by choldgraf** [comment] 2020-06-12 17:03
hmm, could this be a browser issue? this is what I see:

![image](https://user-images.githubusercontent.com/1839645/84528133-f4799480-ac93-11ea-8b6f-b8193102e707.png)

**Comment by chrisjsewell** [comment] 2020-06-12 17:10
Yep same here. @nathancarter a good way to check out the page styling is using the [Firefox inspector](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Open_the_Inspector). As you can see below the word is given the `bolder` styling.

![image](https://user-images.githubusercontent.com/2997570/84528404-8bb40b80-acd7-11ea-826e-b88135611daa.png)

Note it is also possible to add configuration to jupyter-book/sphinx to override the default CSS

**Comment by nathancarter** [comment] 2020-06-12 18:01
OK that's helpful, but I have to confess I'm completely confused about something else now.

I took your suggestion, created a custom CSS file in my `_static` folder, as the `jupyter-book` docs say to do:

```css
b, strong {
    font-weight: bold;
}
```

I then rebuilt the book and used the Chrome dev tools to verify that the `<strong>...</strong>` tag now has its font weight set to bold due to my custom CSS file.

And yet the page looks exactly the same in Chrome, but looks correct in Firefox.

I'm at a loss.  I realize this is not a `jupyter-book` problem, but if you've got any thoughts based on your knowledge of the styles and tools involved, I'd love to hear!

**Comment by najuzilu** [comment] 2020-06-13 01:25
Interestingly I get something similar with @nathancarter. 

Here's a screenshot of an example:
<img width="230" alt="Screen Shot 2020-06-13 at 11 24 21 AM" src="https://user-images.githubusercontent.com/33075058/84556795-70451100-ad68-11ea-9fd0-f71d4ebf06ef.png">

Now, here's what the same text looks like when I remove the font-family `Lato,sans-serif`:
<img width="230" alt="Screen Shot 2020-06-13 at 11 25 10 AM" src="https://user-images.githubusercontent.com/33075058/84556809-8c48b280-ad68-11ea-8ef9-5e04d9a4c16c.png">

**Comment by choldgraf** [comment] 2020-06-13 02:05
oh ho - maybe it's a fonts issue!

**Comment by nathancarter** [comment] 2020-06-17 18:01
This definitely seems like progress, but I confess that I don't know what to do to solve my problem (which is to make it show up on all browsers).  Should I be changing the theme to use a different font?

**Comment by choldgraf** [comment] 2020-06-17 18:07
well, it's tough to say because it sounds like it is dependent on the user's computer. I think one thing to try is make sure that the fonts used by sphinx-book-theme are on your computer. If not, then install them and see if that fixes it so we can pinpoint the issue. If SBT is using something non-standard then we should switch to whatever the standard is.

**Comment by nathancarter** [comment] 2020-06-21 01:33
I'd want to be sure that anyone viewing my book sees the style as intended, so if there's even a possibility that any normal computer (such as my Mac) doesn't have the fonts to see the styles in my code, I'd want to use a different style.

**Comment by choldgraf** [comment] 2020-06-22 16:02
For sure - we just need to pinpoint what is the style issue that's causing this problem, so that we know what to fix

**Comment by pradyunsg** [comment] 2020-08-06 09:33
This seems to have been fixed by https://github.com/pandas-dev/pydata-sphinx-theme/issues/222.

**Comment by choldgraf** [comment] 2020-08-07 18:57
yep, we just need the pydata theme to release a new version, then bump its dependency in the SBT and we should be good-to-go

**Comment by chrisjsewell** [comment] 2020-09-22 23:27
I believe this is now fixed in by pydata-sphinx-theme v0.4

**Closed by chrisjsewell** 2020-09-22 23:27 UTC

**Comment by nathancarter** [comment] 2020-09-23 13:38
Yes.  Somehow I thought I had replied somewhere and confirmed that this was fixed for me, but I can't find my reply right now.  Either way, thank you all--works great!

**Comment by spring-haru** [comment] 2021-08-23 10:09
I use Github Action to deploy the website, and started having the same problem - bold texts are not different from regular ones. I do not specify versions in `requirements.txt`. On the other hand, NO problem arises if I open locally built `html` files. Just in case, I added the following in `requirements.txt' for Github Action

```
sphinx == 3.4.3
sphinxcontrib-serializinghtml == 1.1.4
sphinx-book-theme == 0.1.0
```
which are equivalent to the environment I used to locally create `html` files. But no difference.

When I open the Github Action-created website, it shows bold texts correctly but for less than half second, and then those texts turn quickly "regular".

**Comment by lucasdekam** [comment] 2021-08-24 12:03
I have the exact same issue. Local building is fine, building using Actions has several issues:
* paragraph breaks removed
* horizontal scroll bar at the bottom of the page
* buttons to navigate to next page look different:
![image](https://user-images.githubusercontent.com/26297437/130612707-14ce0374-e9b5-48d6-93a6-04ba356c2daa.png)
instead of
![image](https://user-images.githubusercontent.com/26297437/130612740-96f04dd7-170a-4404-9123-c5c9fdc98299.png)

Repo: https://github.com/lucasdekam/nb2220-test
Page: https://lucasdekam.github.io/nb2220-test/index.html
