### ISSUE TITLE
Language support is broken - .mo files not bundled with this theme's wheel

### ISSUE THREAD

**Issue by whyjz** [executablebooks/sphinx-book-theme#584] opened 2022-07-10 08:59 UTC
### Describe the bug

**context and bug**
The language support seems not working (or partially working) now when used together with Jupyter Book. No matter what language is set in `_config.yml`, for example:
```
sphinx:
  config:
    language: fr
```
There will still be many words remaining untranslated (i.e. in English). Based on the following example, it seems that it used to work but not anymore.

### Likely diagnosis of problem

There are potentially two problems:

1. `.mo` files are not bundled with this theme. For example, [in this pre-release](https://pypi.org/project/sphinx-book-theme/0.4.0rc1) there are generated language files in `theme/sphinx_book_theme/static/locales/` but they are only `.po` and not `.mo`.

   Here's where the compilation happens:

   https://github.com/executablebooks/sphinx-book-theme/blob/cda3bb5753669c095903986cc0a649ff400fcef1/src/sphinx_book_theme/_compile_translations.py#L62-L73

   It isn't clear why this is happening - the only thing I can think of is that the `glob` isn't picking up the `.po` files at the end only in the build job for some reason? They are there when I build it locally.
2. Some theme wording has likely changed. For example, `Toggle primary sidebar` is (I think) a new phrase that is not in our [inventory of language translation phrases](https://github.com/executablebooks/sphinx-book-theme/tree/master/src/sphinx_book_theme/assets/translations). We should find the new phrases that aren't there, and add them via the instructions in that readme.

### Reproduce the bug

I forked a [Jupyter Book written in French](https://mi-gt-donnees.pages.math.unistra.fr/guide/00-introduction.html) (associated [Github repo](https://github.com/miti-gt-donnees/guide)) and pushed the book to my [Github pages](https://whyjz.github.io/miti-gt-donnees-guide/00-introduction.html) (associated [Github repo](https://github.com/whyjz/miti-gt-donnees-guide)) using exactly the same Github Action.

Screenshot from the original Book pages (last push was on Dec 8, 2021)
![1](https://user-images.githubusercontent.com/19339926/178138050-e87d2ce2-7fba-4020-96bd-607fe87ac9de.png)

Screenshot from the forked Book pages (last push was on Jul 10, 2022)
![2](https://user-images.githubusercontent.com/19339926/178138093-ce905168-bfd1-4343-a1ec-a8bf480f9e9e.png)

You can see while some of the words are translated (e.g. Suivant and juil.), many others are not (Last updated, By, ...).

@pnavaro I would like to ping you here since I used your book as a test case. Maybe you also have some ideas about this? 

### List your environment

Latest version on conda in Dec 8, 2021 vs Jul 10, 2022.

**Comment by pnavaro** [comment] 2022-07-10 10:15
Linked to #538 perharps ?

**Comment by whyjz** [comment] 2022-07-11 07:04
Further digging this today made me realize that it is because of the missing `.mo` files in `${sphinx_book_theme_root}/theme/sphinx_book_theme/static/locales/*/LC_MESSAGES`, as required by [`sphinx.locale.get_translation`](https://www.sphinx-doc.org/en/master/extdev/i18n.html#sphinx.locale.get_translation).

A quick workaround is 
1. go to `${sphinx_book_theme_root}`
2. delete all existing `.po` files by `rm -rf theme/sphinx_book_theme/static/locales/*`
3. run `python _compile_translations.py` and regenerate both the `.po` and `.mo` files. Now it should be no problem to generate a fully translated Jupyter Book.

But here I wonder if we could address this in the next few releases since it is so important for all international JB users. It seems to me that `_compile_translations.py` was executed at build time (so we see `.po` files), but failed to generate `.mo` files for an unknown reason.

**Comment by iasbusi** [comment] 2022-11-02 11:31
Thank a lot for this workaround!
I tried it on Windows (10) and it worked after some additional steps.
Here all the steps I did to get it working.

1. Locate your Sphinx installation. It should be located where you global libraries are located. In case you use a `venv`:  
   `C:\{path to your venv}\Lib\site-packages\sphinx_book_theme\`
2. From there navigate to  
   `sphinx_book_theme\theme\sphinx_book_theme\static\locales`  
   and delete everything inside the folder.
3. Install GetText from <https://gnuwin32.sourceforge.net/packages/gettext.htm>. This is the Windows version of a unixtool for native language support. The executable `msgfrm.exe` is needed from this installation to generate the `.mo` files. Add the `bin` folder of the installation to the `%path%` system variable. In my case the path is `C:\GnuWin32\bin`.
4. Navigate to `sphinx_book_theme\` and locate the file `_compile_translations.py`. Edit the file:  
   Change line 57 from  
   `with out_path.open("a") as f:`  
   to  
   `with out_path.open("a", encoding="utf-8") as f:`  
   and safe it.
5. Open a new terminal window (cmd). Acvtivate your venv if you have one. Now run the python script: `python .\_compile_translations.py`. All the translations should be fine now. Rebuild your Jupyter-Book book.

**Comment by twalen** [comment] 2022-11-04 16:46
The `sphinx_book_theme-0.3.3-py3-none-any.whl` file does not contain `*.mo` files, this can be also resolved by installing sphinx-book-theme from source:

`pip install sphinx-book-theme --no-binary 'sphinx-book-theme'`

**Comment by Gouvernathor** [comment] 2022-11-24 21:04
@iasbusi your 5. doesn't work on my end.
```
C:\Windows\system32>cd C:\Program Files\Python39\Lib\site-packages\sphinx_book_theme

C:\Program Files\Python39\Lib\site-packages\sphinx_book_theme>py ./_compile_translations.py
[SBT]: Compiling translations
C:\Program Files\Python39\Lib\site-packages\sphinx_book_theme\assets\translations\..\..\theme\sphinx_book_theme\static\locales\ar\LC_MESSAGES\booktheme.po
Traceback (most recent call last):
  File "C:\Program Files\Python39\Lib\site-packages\sphinx_book_theme\_compile_translations.py", line 78, in <module>
    convert_json()
  File "C:\Program Files\Python39\Lib\site-packages\sphinx_book_theme\_compile_translations.py", line 66, in convert_json
    subprocess.check_call(
  File "C:\Program Files\Python39\lib\subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Program Files\Python39\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Program Files\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

C:\Program Files\Python39\Lib\site-packages\sphinx_book_theme>
```
The last line means "the specified file is not found".

NB : I'm not using sphinx in the context of a notebook, so apologies if it's the reason, but I doubt it.

**Comment by iasbusi** [comment] 2022-11-28 16:58
I’m not sure why it is not working on your side.
I had no time to reproduce this error.
My first guess is, you did not start the script from the right directory.

Please navigate (with cd on the command prompt) to the directory sphinx_book_theme\ and afterwards try to execute the script again (.\_compile_translations.py).

Regards
Adrian

Von: Gouvernathor ***@***.***>
Gesendet: Donnerstag, 24. November 2022 22:05
An: executablebooks/sphinx-book-theme ***@***.***>
Cc: Busin Adrian (busi) ***@***.***>; Mention ***@***.***>
Betreff: Re: [executablebooks/sphinx-book-theme] Bugged language support? (Issue #584)


@iasbusi<https://github.com/iasbusi> your 5. doesn't work on my end.

C:\Windows\system32>cd C:\Program Files\Python39\Lib\site-packages\sphinx_book_theme







C:\Program Files\Python39\Lib\site-packages\sphinx_book_theme>py ./_compile_translations.py



[SBT]: Compiling translations



C:\Program Files\Python39\Lib\site-packages\sphinx_book_theme\assets\translations\..\..\theme\sphinx_book_theme\static\locales\ar\LC_MESSAGES\booktheme.po



Traceback (most recent call last):



  File "C:\Program Files\Python39\Lib\site-packages\sphinx_book_theme\_compile_translations.py", line 78, in <module>



    convert_json()



  File "C:\Program Files\Python39\Lib\site-packages\sphinx_book_theme\_compile_translations.py", line 66, in convert_json



    subprocess.check_call(



  File "C:\Program Files\Python39\lib\subprocess.py", line 368, in check_call



    retcode = call(*popenargs, **kwargs)



  File "C:\Program Files\Python39\lib\subprocess.py", line 349, in call



    with Popen(*popenargs, **kwargs) as p:



  File "C:\Program Files\Python39\lib\subprocess.py", line 951, in __init__



    self._execute_child(args, executable, preexec_fn, close_fds,



  File "C:\Program Files\Python39\lib\subprocess.py", line 1420, in _execute_child



    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,



FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable







C:\Program Files\Python39\Lib\site-packages\sphinx_book_theme>



The last line means "the specified file is not found".

NB : I'm not using sphinx in the context of a notebook, so apologies if it's the reason, but I doubt it.

**Comment by choldgraf** [comment] 2023-01-26 17:00
I updated the top comment from @whyjz to describe what I think are two potential problems that we need to resolve. Would love help from anybody that knows how to fix this! cc @AakashGfude in case he has cycles to look into this, I'd appreciate it!

**Closed** 2023-02-19 14:45 UTC
Labels: bug
