### ISSUE TITLE
xarray html reprs hidden

### ISSUE THREAD

**Issue by zmoon** [executablebooks/sphinx-book-theme#238] opened 2020-10-22 13:32 UTC
**Describe the bug**

![image](https://user-images.githubusercontent.com/15079414/96878970-7602df80-1449-11eb-94d8-a80163a8eca8.png)

If I disable `display: none !important` for `[hidden]`, they appear properly.
![image](https://user-images.githubusercontent.com/15079414/96878858-4eac1280-1449-11eb-922b-e5caa7a89e21.png)

I don't have this issue with other themes I have tried, such as the rtd theme.

**Comment by choldgraf** [comment] 2020-10-22 15:54
do you have a `hide-outputs` tag associated with that cell? That'd be the reason that something would be hidden by default.

Also it'd help if you can provide a link to a website with this bug / code to reproduce it.

**Comment by zmoon** [comment] 2020-10-22 16:37
Hi @choldgraf, I didn't add any tags to that cell. When I use the rtd theme, the xarray.Dataset repr is not hidden.

I don't currently have a way to share the webpage, but I am working on that. It is a just a simple notebook in Jupytext percent format, included in my Sphinx docs build using nbsphinx.

**Comment by choldgraf** [comment] 2020-10-22 18:27
I guess I am trying to figure out what you mean by:

```
If I disable display: none !important for [hidden], they appear properly.
```

How is a "hidden" class being attached to the output?

**Comment by zmoon** [comment] 2020-10-22 18:40
It looks like it always has `hidden` attribute, but the rtd theme just doesn't do anything with it:

with book theme
![image](https://user-images.githubusercontent.com/15079414/96914785-71ebb780-1473-11eb-96ad-64b4576113d0.png)

with rtd theme
![image](https://user-images.githubusercontent.com/15079414/96915151-e9214b80-1473-11eb-82c3-270ea784057b.png)

**Comment by choldgraf** [comment] 2020-10-22 18:44
hmmmm....so I guess that `hidden=""` is being treated as a CSS class? I hadn't heard of that before. Raise it with them and see if they think this is expected behavior, and if so I can look into how we can get this working more properly in the `sphinx-book-theme`

**Comment by zmoon** [comment] 2020-10-22 18:59
Looks like there is already an open issue: https://github.com/pydata/xarray/issues/4320

**Comment by fmaussion** [comment] 2020-10-22 19:54
Most of the xarray folks have little experience with CSS (except maybe @benbovy who wrote html repr), so if you have a suggestion or a fix I'm sure it'll be much appreciated!

**Comment by benbovy** [comment] 2020-10-22 20:08
It looks like another side effect of https://github.com/pydata/xarray/pull/4053. 

We could revert this dirty hack, but then the rendering issues will come back in other Jupyter Front-ends such as Notebook / Lab.

I don't really know what to do to solve this unfortunately 😕.

**Comment by choldgraf** [comment] 2020-10-22 20:20
Hmmm - yeah I mean it seems like the behavior of "not showing up when the `hidden` attribute is there" is actually the _correct_ behavior (at least, [according to w3](https://www.w3schools.com/tags/att_hidden.asp)...so I don't think that we could work around this on the sphinx-book-theme side. What is `hidden` meant to accomplish within the xarray output?

**Comment by benbovy** [comment] 2020-10-22 21:29
The 'hidden' attribute is there to prevent showing the html repr when a notebook is not trusted. 

Jupyter Notebook and Lab do not inject the repr's CSS if that's the case, and without CSS, xarray's html reprs look totally ugly and unusable (like it's still the case in notebooks viewed on GitHub).

The 'hidden' attribute of an element should be ignored by browsers if there's a CSS display property defined for that element. We use this as a (weak) trick in xarray to show the repr when the repr's CSS is injected. 

But in this case, it doesn't work because (I think) bootstrap 4 explicitly sets 'display: none' for all elements having the HTML 'hidden' attribute.

Maybe there's a way to add in this theme some CSS that supersedes bootstrap's definitions?

Probably we could add an extra display option in xarray as a flag to enable/disable this trick, if that could help...

**Comment by choldgraf** [comment] 2020-10-22 21:35
ohh interesting - so if I understand you:

- w3 says you should treat "hidden" to say "hide this element entirely", _unless_ another class explicitly sets the `display:` property
- xarray thus uses `hidden=""` *along with* a CSS class that has `display:` and thus overrides the `display: none` behavior?

If so, what is the CSS class that xarray uses, and we can special-case it in the theme (probably we'll want to do this in the [pydata theme](https://pydata-sphinx-theme.readthedocs.io/), since I could see this issue popping up in other pydata projects).

**Comment by zmoon** [comment] 2020-10-22 21:53
Can confirm Bootstrap 4 sets `display: none !important` for `hidden` attribute:

https://github.com/twbs/bootstrap/blob/v4.5.3/dist/css/bootstrap.css#L353-L355

**Comment by benbovy** [comment] 2020-10-22 21:55
Yes that's correct, although I admit it's very confusing and I don't really like it (https://html.spec.whatwg.org/multipage/interaction.html#the-hidden-attribute).

I think all you need here is to add the line below in this theme's CSS (given that it is injected after Bootstrap's CSS)

```css
.xr-wrap { display: block !important }
```

**Comment by choldgraf** [comment] 2020-10-22 21:56
ok cool, I am happy to special-case `xarray` since y'all are part of the pydata open source family 💞

**Comment by benbovy** [comment] 2020-10-22 22:05
Yeah longer term it would be great if we could somehow inject custom CSS once and safely in notebooks (if that's possible). Right now the whole CSS is embedded with every repr shown in output cells, which is not ideal either.

**Comment by choldgraf** [comment] 2020-10-22 22:08
hey whatever works :-)

**Comment by benbovy** [comment] 2020-10-22 22:12
Now that Jupyterlab 3 makes easier the installation of extensions with pip/conda, I'm wondering if we could eventually ship a lightweight extension with xarray...

**Comment by choldgraf** [comment] 2020-10-22 22:17
that's a really interesting idea - I think this would totally work if that pattern becomes a community standard across other UIs (and if you particularly care about other UIs as well, like colab / vscode / etc...and if you don't care about those UIs, then either way yes I think this would be a great use of the new jupyterlab extension mechanism)

**Comment by choldgraf** [comment] 2022-02-20 20:31
closing this as we should now properly display xarray via the pydata theme, feel free to re-ping here if it doesn't work in the future. Ref: https://pydata-sphinx-theme.readthedocs.io/en/latest/demo/theme-elements.html?highlight=xarray#xarray

**Closed by choldgraf** 2022-02-20 20:31 UTC
Labels: bug
