### ISSUE TITLE
Contents list highlighting seems to be indexed incorrectly

### ISSUE THREAD

**Issue by CalMacCQ** [executablebooks/sphinx-book-theme#659] opened 2022-12-12 12:53 UTC
Hi ,

### Describe the bug

**context**
I came across what appears to be a minor issue with the contents list highlighting.

When I click on an entry in the contents list on the right hand side of the screen the incorrect entry seems to be highlighted. I'm not completely sure if this is a bug or intended behaviour.

 I also noticed this in the sphinx_book_theme documentation.

**expectation**
(see screenshot) I expect that when I click on `1.7.3 (October 2022)` the page navigates to the heading `1.7.3 (October 2022)` and the `1.7.3 (October 2022)` entry in the contents list is highlighted on the right.

**bug**
(see screenshot) When I click on `1.7.3 (October 2022)` the page successfully navigates to the October entry but the ` 1.8.0 (November 2022)` item is highlighted on the right. 

It seems the entry above the one the user clicks on is highlighted.

![Screenshot 2022-12-12 at 13 03 44](https://user-images.githubusercontent.com/93673602/207052042-b13df09d-2b39-4a49-9eff-2f1ec565b327.png)

### Reproduce the bug

1. Go to sphinx book theme documentation -> https://sphinx-book-theme.readthedocs.io/en/stable/
2. click on "getting started"
3.  On the contents list on the right click on "Customize your left sidebar"
4. note how the page navigates to the correct heading but  the above entry "Add a source repository button to your theme" is highlighted on the right.

Thanks :)

**Comment by Elijahh177** [comment] 2022-12-13 13:59
Possible duplicate of #545

**Comment by choldgraf** [comment] 2023-01-07 13:12
Yep - this is now fixed in upstream and will be resolved in the next release (after the pydata theme releases):

- https://github.com/executablebooks/sphinx-book-theme/issues/545

**Closed by choldgraf** 2023-01-07 13:12 UTC
Labels: bug
