### ISSUE TITLE
Implement sidenotes

### ISSUE THREAD

**Issue by akhmerov** [executablebooks/sphinx-book-theme#378] opened 2021-08-15 14:13 UTC
### Describe the enhancement you'd like

Tufte CSS [recommends](https://edwardtufte.github.io/tufte-css/) (see "Sidenotes: Footnotes and Marginal Notes") numbered sidenotes instead of footnotes.

### Does this solve a specific problem?

The current workflow in sphinx-book-theme for checking a footnote is:

1. Click on the footnote link
2. Reorient yourself on the page
3. Figure out that you have to click again to get back

Sidenotes avoid these steps.

### What alternatives exist?

The closest alternative in sphinx-book-theme is margin notes, but it isn't quite the same due to the lack of references.

**Comment by choldgraf** [comment] 2021-08-15 16:42
Definitely agree with this idea - it's just waiting for a champion to pick it up and try implementing. If we implement it in this theme, I think it'd be good to also think about generalizing to a standalone package (e.g. `sphinx-margin`) that could define these directives.

Gonna close this one though, as I think it's a dupe of https://github.com/executablebooks/jupyter-book/issues/598

**Closed by choldgraf** 2021-08-15 16:42 UTC
Labels: enhancement
